config/routes.rb
Rails.application.routes.draw do
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check
  root "students#index"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :adresse, :plz, :ort, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studentenverwaltung</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :adresse, style: "display: block" %>
    <%= form.text_field :adresse %>
  </div>

  <div>
    <%= form.label :plz, style: "display: block" %>
    <%= form.number_field :plz %>
  </div>

  <div>
    <%= form.label :ort, style: "display: block" %>
    <%= form.text_field :ort %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit class: "waves-effect waves-light btn" %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Adresse:</strong>
    <%= student.adresse %>
  </p>

  <p>
    <strong>Plz:</strong>
    <%= student.plz %>
  </p>

  <p>
    <strong>Ort:</strong>
    <%= student.ort %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= student.phone %>
  </p>
</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back", students_path, class: "waves-effect waves-light btn" %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<%= link_to "New", new_student_path, class: "waves-effect waves-light btn" %>

<br>

<div id="students">
  <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Adresse</th>
      <th>PLZ</th>
      <th>Ort</th>
      <th>Email</th>
      <th>Phone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.adresse %></td>
      <td><%= student.plz %></td>
      <td><%= student.ort %></td>
      <td><%= student.email %></td>
      <td><%= student.phone %></td>
      <td><%= link_to "Show", student, class: "waves-effect waves-light btn" %></td>
      <td><%= link_to "Edit", edit_student_path(student), class: "waves-effect waves-light btn" %></td>
      <td><%= button_to "Destroy", student, method: :delete, class: "waves-effect waves-light btn" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="col s12 m7">
    <h2 class="header">Horizontal Card</h2>
    <div class="card horizontal">
      <div class="card-stacked">
        <div class="card-content">
          <%= render @student %>
        </div>
        <div class="card-action">
          <%= link_to "Edit", edit_student_path(@student) %> 
        </div>
      </div>
    </div>
  </div>

<div>
  <%= link_to "Back", students_path, class: "waves-effect waves-light btn"%>
</div>